name: CI/CD

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set short git sha
        id: tags
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            APP_URL=lat.rbkr.xyz
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/learnanything-tech:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/learnanything-tech:${{ steps.tags.outputs.sha_short }}
            
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/master'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set short git sha
        id: tags
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "IMAGE_TAG"
          replace: ${{ steps.tags.outputs.sha_short }}
          include: "kubernetes/*/01-deployment.yml"
          
      - name: Deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f kubernetes/prod/
